### ISSUE TITLE
Solve all the Questions of Chapter 6(Functions and Pointers)

### ISSUE THREAD

**Issue by debajit13** [debajit13/Let-Us-C-solution#4]
***Questions are given in Chapter 6 folder***

**Comment by lostgirljourney** [comment]
I'm working on it @debajit13 da!

**Comment by debajit13** [comment]
Issue resolved by @lostgirljourney. Thanks for the contribution.

**Comment by debajit13** [comment]
This issue is not solved by anyone.

**Comment by deepdhar** [comment]
I will work on this @debajit13 da

**Comment by debajit13** [comment]
okay bro, sure
